{
 "title": "SkyhookDM-Arrow",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{device=\"nvme0n1\"}[5m])"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"eno1d1\"}[5m])"
    }
   ]
  },
  {
   "title": "Client CPU Usage (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(avg by (instance) (rate(node_cpu_seconds_total{job=\"node\",mode=\"user\",instance=\"ms1243.utah.cloudlab.us:9100\"}[1m])) * 100)"
    },
    {
     "expr": "(avg by (instance) (rate(node_cpu_seconds_total{job=\"node\",mode=\"user\",instance=\"ms1243.utah.cloudlab.us:9100\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "Storage CPU Usage (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(avg by (instance) (rate(node_cpu_seconds_total{job=\"node\",mode=\"user\",instance!=\"ms1243.utah.cloudlab.us:9100\"}[1m])) * 100)"
    },
    {
     "expr": "(avg by (instance) (rate(node_cpu_seconds_total{job=\"node\",mode=\"user\",instance!=\"ms1243.utah.cloudlab.us:9100\"}[1m])) * 100)"
    }
   ]
  }
 ]
}